# Turn on validation, so we can use import:
version: ~> 1.0

rvm:
- 2.5.1

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

services:
- postgresql

before_script:
- npm install
- npm install bower
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:setup

script:
- APPMAP=true bundle exec rake spec
- APPMAP=true bundle exec rake jasmine:ci
- APPMAP=true bundle exec rake cucumber || true
