# Turn on validation, so we can use import:
version: ~> 1.0

rvm:
- 2.5.1

services:
- postgresql

before_install:
- yes | gem update --system --force
- gem install bundler:1.17.2

before_script:
- npm install
- npm install bower
- bundle exec rails db:migrate
- bundle exec rake db:setup

script:
- bundle exec rake spec
- bundle exec rake jasmine:ci
- bundle exec rake cucumber
